### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by philled** [stevelacy/EasyCap#10]
I have an EasyCAP card that I'm trying to get working on an Ubuntu 18.04 machine. yesterday I found somagic Debian packages, installed them, got the firmware off my CD etc and was quite excited as I was able to capture video from an old Digital 8 home video tape. But I was unable to capture any audio. So I started searching and found multiple code repositories for somagic and some of them seemed to have audio, some didn't. It was very confusing and I didn't know which was the best one to use etc. Then I found this one which appears to be set up to be THE place to go for somagic. Is that correct - have I come to the right place?

Second question is, will I be able to capture the audio on the tapes with this version of somagic? I've seen some places that say audio isn't supported and others that say it is. 

Third question is, how do I install this version instead of the ones I installed yesterday. Should I just uninstall the Debian packages I got working yesterday and install these? What about the firmware?

Sorry for all the newbie questions!

**Comment by stephenlacy** [comment]
This adapter does capture audio for the easycap devices I used, I am assuming that it will also capture audio for most devices unless they are built not supporting any audio capture (or one that was custom for that device).

You do not need to uninstall your currently installed debian packages -- but I would highly recommend doing a clean uninstall of all easycap/somagic packages first to ensure that this package is the one used.

Try compiling from source just in case the bin file is not supported on your system.
