### ISSUE TITLE
ARM suport

### ISSUE THREAD

**Issue by ahwelp** [stevelacy/EasyCap#11]
This error shows when somagic-init is executed.
`bash: /usr/local/bin/somagic-init: cannot execute binary file: Exec format error` 

I think the firmware is not compatible with the ARM architecture. I am using a RaspberryPi3 and a 4CH capture card(https://images-americanas.b2w.io/produtos/01/00/sku/9403/8/9403895_1GG.jpg).

Unfortunatly, I have no idea how to program on C and what is needed to convert and recompile the source.

**Comment by stephenlacy** [comment]
it is compiled on linux64. 
To compile for another arch please use the installation from source instructions: https://github.com/stevelacy/EasyCap/blob/master/documentation/installation.md#compile-from-source
