### ISSUE TITLE
how to compile for ARM (raspberry)?

### ISSUE THREAD

**Issue by allegfede** [stevelacy/EasyCap#12]
hello.
I have a misterious ezcap 534d:0021 with nothing more than the number.

it seems to "quite" work on raspbian, but i cannot set video standard and other weird thing.

do you think i can solve with your software in an arm enviroment?

cheers

**Comment by stephenlacy** [comment]
You should be able to compile from source: https://github.com/stevelacy/EasyCap/blob/master/documentation/installation.md#compile-from-source
