### ISSUE TITLE
Please add support for Terratec AV Grabster 300 MX

### ISSUE THREAD

**Issue by linnex81** [stevelacy/EasyCap#4]
Hi,

the Terratec AV Grabster 300 MX is virtually identical in HW to the Somagic EasyCap.
Unfortunately I could not find any driver / linux support for this device so far but modifying 
somagic-capture.c slighty => and the device was working.

It just has a different vendor id (0x0ccd) and product (0x00b6).
It does not seem to require firmware initialization (at least for me)

but using:
```
// #define VENDOR 0x1c88
# define VENDOR 0x0ccd
# define PRODUCT_COUNT 4

static const int PRODUCT[PRODUCT_COUNT] = {
//  0x003c,
    0x00b6,
```

I finally got it to work.

Would be great if you could add it as supported device as well. Thx

Linne

**Comment by stephenlacy** [comment]
Want to send a PR with that option?

**Comment by linnex81** [comment]
hi Steve, sorry, what does PR stand for?

Am 13.09.2016 um 01:04 schrieb Steve Lacy:

> Want to send a PR with that option?

**Comment by stephenlacy** [comment]
pull request

**Comment by stephenlacy** [comment]
I am closing this issue as I am not adding support for devices I do not own
