### ISSUE TITLE
Video / Sound desynchronization.

### ISSUE THREAD

**Issue by ArthurSonzogni** [stevelacy/EasyCap#7]
I have converted 20 videos of length ~4h. After some minutes, it appears a Video / Sound desynchronization.
The video data is often shorter than the sound data. So, I get the video before the sound when I read the file. Maybe the computer or the usb device is too slow and some video images are dropped.

I think I need to synchronize the two source during acquisition. Maybe by dropping some "music frames" such that there is almost the same number of frames produced.

Maybe I will try to improve it. So I put an issue.
I haven't really read the code yet. If you have any ideas or suggestion, I would love getting them.

Thanks!

**Comment by stephenlacy** [comment]
I am so sorry, I thought I commented on this a year ago...

Can you stop/start the video stream in process while it is capturing? It might be a 1 sec break in video frames, but should reset the audio to be in tune with the video.
I honestly haven't captured more than 30minutes at a time with audio, any longer was just video that I process into photo frames. (motion)

**Comment by ArthurSonzogni** [comment]
I Steve,

Yes, I think I could stop/restart the video stream 1 second every 10 minutes to resynchronize the video/audio. That's  a good idea!
