### ISSUE TITLE
Does this work with the new 4ch Version?

### ISSUE THREAD

**Issue by AlessandroAU** [stevelacy/EasyCap#9]
I have read that this should work using the 4ch version of the somagic capture card. However it appears that the 4ch version is not really 4ch but simply has a mux that switches the input.

It now appears that there is a true 4ch real-time version! 
and on board sdram?

https://www.ebay.com.au/itm/4CH-Digital-Video-Audio-Capture-Card-4Channel-120fps-Real-Time-USB-DVR-Recorder/122237523166?hash=item1c75ec94de:g:ozgAAOSwZB9aLpA6

chipset is SMI2022, which I cannot find details about, but it appears to use the same driver?

I have one but it does not seem to work, firmware extraction works fine and I can somagic-init the device, however it errors when attempting to capture.
![somagic-lsusb](https://user-images.githubusercontent.com/22009829/38023235-0ffcf878-32c5-11e8-90c5-fe9102093db9.png)
![somagic-run](https://user-images.githubusercontent.com/22009829/38023238-1191ca60-32c5-11e8-9c6a-80ef09714dd7.png)
![4chsomagic](https://user-images.githubusercontent.com/22009829/38023266-2a359a9c-32c5-11e8-9d6f-926dc16fc6f1.jpg)

**Comment by stephenlacy** [comment]
I have not tested it with a 4ch, where did you get `somagicrun` from? It looks like it's looking for an existing process or possibly a binary.

**Comment by AlessandroAU** [comment]
Hi, It's just a script of the commands in the documentation to get a stream going
![somagicrun](https://user-images.githubusercontent.com/22009829/38057718-a32d63c2-3323-11e8-973b-a36161aa2414.png)

**Comment by stephenlacy** [comment]
What is the output of `sudo somagic-init` and `sudo somagic-capture`

**Comment by AlessandroAU** [comment]
Same result sadly
![outputtest](https://user-images.githubusercontent.com/22009829/38072350-30092a3e-3369-11e8-8035-5bf2376ab09f.png)

**Comment by maxmax91** [comment]
Do you have any news about 4ch version?

**Comment by stephenlacy** [comment]
I am concluding that it does not work with the 4ch
